#############################################################
# Megan Brudz-Rodríguez
# GSE53798 - CSC 450
# Summary from GEO:
# We used global gene expression profiles from human B-cell cell
# lines to generate gene expression signatures for prediction
# of response to the drugs cyclophosphamide, doxorubicin or
# vincristine. The signatures were validated in two publicly
# available clinical cohorts.
# https://www.ncbi.nlm.nih.gov/geo/query/acc.cgi?acc=gse53798
#############################################################

# 1 libraries
library(GEOquery)
library(limma)

PL = getGEO("GPL570")
PL = Table(PL)


# 2 download process data, in 1.4 file
GSE53798 = getGEO("GSE53798")
GSE53798.expr = exprs(GSE53798[[1]])
GSE53798.p = pData(GSE53798[[1]])


# 3 boxplot
boxplot(GSE53798.expr, main = "Gene expression profiles from malignant B cell lines", xlab = "Sample",
        ylab = "Log2 expression",names = NULL )

# no need to normalize data

# 4 number of samples and probes
# number of samples
ncol(GSE53798.expr)

# number of probes
nrow(GSE53798.expr)


# 5 comparing 
cellfrac = as.character(GSE53798.p$characteristics_ch1.8)

# separate "vincristine" from Resistant and Sensitive found via "View(GSE53798.p)"
sample.names = as.character(cellfrac)
s = strsplit(sample.names, ": ")
get.last <- function(x) {return(x[[2]])}  
cellfrac = sapply(s, get.last)

# amount in control and treatment group
sum(cellfrac == "Resistant")
sum(cellfrac == "Sensitive")


# 6 differentially expressed probes
groups = GSE53798.p$characteristics_ch1.8
levels(groups) = c("-" ,"Intermediate", "Resistant", "Sensitive")

# remove "Intermediate" and "-"
index = groups != "Intermediate"
groups = groups[index]
GSE53798.expr = GSE53798.expr[,index]
index = groups != "-"
groups = groups[index]
GSE53798.expr = GSE53798.expr[,index]

groups = as.character(groups)

design = model.matrix(~0+groups)
head(design)

colnames(design) = c("resistant", "sensitive")
fit = lmFit(GSE53798.expr, design)
head(fit$coefficients)
head(fit$sigma)

contrast.matrix <- makeContrasts(resistant - sensitive,levels=design)

fit = contrasts.fit(fit, contrast.matrix)
head(fit$coefficients)
head(fit$sigma)

fit = eBayes(fit)

tt = topTable(fit,sort.by = "p")

tt.100 = topTable(fit,sort.by = "p", number = 100)
nrow(tt.100)

# 7 top probes
tt.100 = topTable(fit, number = 50)
set3 = tt.100
head(tt.100) # top probes
# top 3 probes w/ logFC & adj.p-val
tt.100 = topTable(fit, number = 3)
tt.100 = head(tt.100) # top 50 probes
cols = c(1,5)
tt.100[1:3, cols]
adj = tt.100$adj.P.Val
adj[3] # value of FDR using final adj.P.Value

# 8 probe with lowest adjusted p-val: 
min(tt.100$adj.P.Val)
logFC = tt.100[1,]$logFC
FC = 2**logFC
boxplot(tt.100[1,], main = "Fold Change = 1.871688", xlab = "Probe 1555464_at",
        ylab = "Expression")

# 9 find probe that corresponds to specific gene, get GPL
annotation(GSE53798[[1]])
# get platform for this dataset (the 1st dataset in the list)
platform = annotation(GSE53798[[1]])

# 10 download GPL
GPL = getGEO(platform)

# 11 top genes corresponding to all probes
genes.db = Table(GPL)
m = match(rownames(tt.100), genes.db$ID)
genes = as.character(genes.db$'Gene Symbol'[m])[]
keep = genes!=""
genes = genes[keep]
genes = strsplit(genes, " /// ")
get.first <-function(x) {
  x[1]
}
genes = sapply(genes, get.first)
genes = unique(genes)
write.table(genes[2:4], row.names = FALSE, quote = FALSE)

# 12 top 2 genes according to gene cards
# ATP5J and CMPK1


# 13 using DAVID for Gene Ontology (GO) terms of KEGG
# ATP5J is ATP synthase, H+ transporting, mitochondrial
# F0 complex, subunit F6.  Mitochondrial membrane ATP
# synthase (F(1)F(0) ATP synthase or Complex V) produces
# ATP from ADP in the presence of a proton gradient across
# the membrane which is generated by electron transport
# complexes of the respiratory chain.

# CMPK1 is cytidine monophosphate (UMP-CMP) kinase 1,
# cytosolic.  It encodes one of the enzymes required for
# nucleic acid biosynthesis.  The enzyme catalyzes the
# transfer of a phosphate group from ATP to CMP, UMP, or
# dCMP, to form the corresponding diphosphate nucleotide.


# 14 heatmap
# ten probes are from tt
probes3 = rownames(tt)


col.heat = colorRampPalette(c("yellow", "blue"))(200)
m = match(probes3, rownames(GSE53798.expr))

m.genes = match(probes3, PL$ID)
genes = PL$`Gene Symbol`[m.genes]
genes = paste0(genes, " (", probes3, ")")

rownames(GSE53798.expr)[m] = genes

col.response = as.integer(factor(groups))
col.response = c("darkred","darkgreen")[col.response]
table(col.response)

heatmap(GSE53798.expr[m,], col=col.heat, ColSideColors = col.response)

#venn diagram
area3 = probes3
